# Generated by Django 6.1 on 2026-08-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_number', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('conductivity_raw_mScm', models.FloatField()),
                ('temperature_C', models.FloatField()),
                ('conductivity_temp_adjusted_mScm', models.FloatField()),
                ('milk_pH', models.FloatField()),
                ('somatic_cell_count', models.FloatField()),
                ('milk_yield_L', models.FloatField()),
                ('clotting', models.BooleanField(default=False)),
                ('as7343_F1', models.FloatField()),
                ('as7343_F2', models.FloatField()),
                ('as7343_FZ', models.FloatField()),
                ('as7343_F3', models.FloatField()),
                ('as7343_F4', models.FloatField()),
                ('as7343_F5', models.FloatField()),
                ('as7343_FY', models.FloatField()),
                ('as7343_FXL', models.FloatField()),
                ('as7343_F6', models.FloatField()),
                ('as7343_F7', models.FloatField()),
                ('as7343_F8', models.FloatField()),
                ('as7343_NIR', models.FloatField()),
                ('as7343_VIS', models.FloatField()),
                ('as7343_FD', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='cows.cow')),
            ],
        ),
    ]
